### PR TITLE
Euler function in java

### PR DESCRIPTION
**Pull request by ishitakeshawani**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I write Solution of Euler's totient function in java.

### Checklist

- [✔ ] I've read the contribution guidelines.
- [✔ ] I've checked the issue list before deciding what to submit.
- [✔ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This is the solution of the issue no #445

### CODE REVIEW

**Comment by siddharth25pandey** [comment]
@Ishita1608 Copied from [this](https://www.geeksforgeeks.org/eulers-totient-function/), only variable name is changed.
* Try to solve it by your own & there is a better approach exists then this solution.

**Comment by ishitakeshawani** [comment]
this is not copied. I read about Euler function that can be solved by finding gcd and this function count numbers which are coprime .if I use the same approach you can not say that is copied.i know I can find the optimum solution of this.and this time I did my search to Euler function.it is not fair @siddharth25pandey .

**Comment by siddharth25pandey** [comment]
@Ishita1608 if you think it's not copied than send the PR again with best optimal solution & briefly describe the Concept with complete Explanation as comment in code.
Hope you understand

**Comment by ishitakeshawani** [comment]
sure! I will do.

**Pull request closed without merging**
